### ISSUE TITLE
Add Support for Multiple Units of Measurement (B, KB, MB, GB, TB)

### ISSUE THREAD

**Issue by TashaPr** [e-vasiltsov/fs-size-checker#24]
**Currently,** **fs-size-checker** supports size checking but only with a single unit of measurement (bytes). To enhance usability and flexibility, it would be beneficial to add support for additional units: KB, MB, GB, and TB.

**Proposed Feature**
Implement a feature that allows users to specify the unit of measurement for file size checks. For example:

--max-size 50 --unit KB to check if file sizes exceed 50 KB.
--max-size 100 --unit MB for 100 MB limits, etc.
**Requirements**
**Command-Line Option:** Modify the CLI to accept a --unit option with values B, KB, MB, GB, TB.
**Unit Conversion Logic:** Implement logic to handle unit conversions, ensuring accurate size comparisons across different units.
**Error Handling:** Validate the unit parameter, providing clear error messages if an unsupported unit is specified.
**Documentation:** Update the README to reflect the new options and usage examples.
**Tests:** Add tests for each unit to confirm correct functionality and validation.
This feature would make **fs-size-checker** more versatile, especially in cases where large files or directories are involved, by allowing users to use more readable size thresholds.

Let me know if you'd like more details on the proposed implementation approach!

**Comment by e-vasiltsov** [comment]
@TashaPr Yes, please go ahead with this feature! Just ensure it follows best practices: keep it SOLID, DRY, and KISS, with a clean OOP structure. Looking forward to your PR!
